### ISSUE TITLE
CTRL-C still does not work

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4207] opened 2023-07-04 14:18 UTC
```
^C2023-07-04T14:17:24.256672Z  INFO massa_node: interrupt signal received
2023-07-04T14:17:24.257243Z  INFO massa_bootstrap::server: ip white/blacklist updater exited cleanly
2023-07-04T14:17:24.258616Z  INFO massa_bootstrap::server: bootstrap server stopped
2023-07-04T14:17:24.258631Z  INFO massa_node: Start stopping API's: gRPC, EXPERIMENTAL, PUBLIC, PRIVATE
2023-07-04T14:17:24.258644Z  INFO massa_grpc::server: gRPC API stop signal sent successfully    
2023-07-04T14:17:24.258680Z  INFO massa_api: API stop signal sent successfully
2023-07-04T14:17:24.259590Z  INFO massa_node: API | EXPERIMENTAL JsonRPC | stopped
2023-07-04T14:17:24.259598Z  INFO massa_api: API stop signal sent successfully
2023-07-04T14:17:24.259801Z  INFO massa_node: API | PUBLIC JsonRPC | stopped
2023-07-04T14:17:24.259809Z  INFO massa_api: API stop signal sent successfully
2023-07-04T14:17:24.260603Z  INFO massa_node: API | PRIVATE JsonRPC | stopped
2023-07-04T14:17:24.260704Z  INFO massa_metrics::server: METRICS | server stopped
2023-07-04T14:17:24.262752Z  INFO massa_factory_worker::manager: stopping factory...
2023-07-04T14:17:24.264724Z  INFO massa_factory_worker::manager: factory stopped
2023-07-04T14:17:24.264731Z  INFO massa_protocol_worker::manager: stopping protocol module...
Stopping protocol
Removing connection from: PeerId { public_key: P1kKfgrCveVnosUkxTzaBw5cf9f2cbTvK3R5Ssb2Pf76au8xwmH }
Stoppeed network controller
2023-07-04T14:17:24.282528Z  WARN massa_protocol_worker::handlers::operation_handler::retrieval: Failed to send AskForOperations message to peer: Send error: Peer isn't connected anymore
2023-07-04T14:17:24.283129Z  INFO massa_protocol_worker::handlers::operation_handler::retrieval: Stop operation retrieval thread
^C2023-07-04T14:17:26.151191Z  INFO massa_protocol_worker::handlers::operation_handler::propagation: Stop operation propagation thread
Stopped operation handler
2023-07-04T14:17:26.177994Z  INFO massa_protocol_worker::handlers::endorsement_handler::retrieval: Stop endorsement retrieval thread
2023-07-04T14:17:26.180863Z  INFO massa_protocol_worker::handlers::endorsement_handler::propagation: Stop endorsement propagation thread
Stopped endorsement handler
2023-07-04T14:17:26.241309Z  INFO massa_protocol_worker::handlers::block_handler::retrieval: Stop block retrieval thread from command receiver
2023-07-04T14:17:26.319645Z  INFO massa_protocol_worker::handlers::block_handler::propagation: Stop block propagation thread
Stopped block handler
Stopped peer handler
2023-07-04T14:17:26.406373Z  INFO massa_consensus_worker::manager: stopping consensus worker...    
2023-07-04T14:17:27.175777Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:29.400148Z  WARN massa_metrics::survey: PEERNET | No data sent or received since 5s
2023-07-04T14:17:29.810046Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
^C2023-07-04T14:17:32.442692Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:34.400231Z  WARN massa_metrics::survey: PEERNET | No data sent or received since 5s
2023-07-04T14:17:35.113319Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:37.811870Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:39.400365Z  WARN massa_metrics::survey: PEERNET | No data sent or received since 5s
2023-07-04T14:17:40.516550Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:43.351183Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:44.400448Z  WARN massa_metrics::survey: PEERNET | No data sent or received since 5s
2023-07-04T14:17:46.175976Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:48.894026Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error    
2023-07-04T14:17:49.400562Z  WARN massa_metrics::survey: PEERNET | No data sent or received since 5s
2023-07-04T14:17:51.578452Z  WARN massa_consensus_worker::worker::main_loop: Error in consensus: Protocol error An error occurred during channel communication: send_wishlist_delta command send error   
[... continues like that ... ]
```

**Comment by AurelienFT** [comment] 2023-07-04 14:42
Closing as a duplicate of https://github.com/massalabs/massa/issues/4121

**Closed by AurelienFT** 2023-07-04 14:42 UTC
