### ISSUE TITLE
Sending private keys over insecure connection

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa#1999] opened 2021-12-14 16:16 UTC
Unless I'm missing something `add_staking_private_keys sends private keys over insecure HTTP connection... I believe it is a VERY BAD idea.

https://github.com/massalabs/massa/blob/46cdb7db16e7d15236f59fcf45d9f73d6ec4dc44/massa-client/src/rpc.rs#L85

Originally posted here https://gitlab.com/massalabs/massa/-/issues/474 by @Vadiml1024

**Comment by AureliaDolo** [comment] 2021-12-14 16:19
We can at least add a section in the FAQ to warn users.

**Comment by damip** [comment] 2021-12-15 15:41
We will tackle this during the big refactoring targeting TEST.7.0.
It goes hand-in-hand with client wallet file encryption, node staking key file encryption and authorized TLS on the private API.

**Comment by yvan-sraka** [comment] 2021-12-15 17:42
Oh wow !? how do you want to manage authentification?

**Comment by damip** [comment] 2021-12-16 13:23
@yvan-sraka TLS client authentication

**Comment by Vadiml1024** [comment] 2021-12-16 17:41
While it will be a big change, maybe the best approach would be to use libp2p for communication.
As of today it is state of the art in secure p2p communications and there is Rust API for it.

**Comment by damip** [comment] 2021-12-16 18:05
@Vadiml1024  here we are talking about securing the link between the client and the node's API, it's a normal client-server HTTP connection (not P2P), and I think it's good to add (optional) encryption there to avoid eavesdropping of private keys.

As for adding encryption in the P2P link between nodes, I'm less convinced. Nodes don't know or trust each other, so no sensitive information transits between nodes, and identity verification is not possible. Adding encryption there would increase latency, bandwidth and CPU usage with no obvious security benefits.

**Comment by Vadiml1024** [comment] 2021-12-24 02:53
@damip Thank you for your response,  you're right about p2p.
I've probably missed something, but after some browsing of source code, I see that private keys received by the **node** are used only to derive the corresponding public key which is used for address derivation.
If this is the case, maybe the **wallet** does not need to send them in the first place? Maybe sending public keys will be sufficient?

**Comment by damip** [comment] 2021-12-24 08:20
@Vadiml1024 private keys in the node are used in multiple places:
* The autogenerated key in node_privkey.key is used to derive the nodeId, perform protocol bootstrap handshake signatures, sign bootstrap messages, and perform node message signature for proof of nodeid ownership
* the private key sent when registering a staking key is used for deriving an address to know when this key is selected for block and endoresement production, and then it is used to signed the produced blocks and endorsements

**Comment by Vadiml1024** [comment] 2021-12-28 17:56
Ok, I see and i've found the code which is using private keys.
If I understand correctly one node will be used by multiple client wallets, in that case,
an attacker who succeeded in compromising one node will have access to all these client wallets...
Kind of dangerous? Am I missing something? How this threat can be mitigated?
Btw - Do you have some kind of document describing software design?

**Comment by damip** [comment] 2021-12-29 07:19
@Vadiml1024 the public api of the node can be used by various untrusted clients but it doesn't give access to the keys. The node operator can also prevent access to the public api. The private api allows the local operator to add staking keys to the node.
For decentralization, we deliberately chose to not support delegation and have people always stake with their own node and keys.
For safety, you are free to stake with one wallet, then move accumulated funds to another non-staking one (you don't have to register all your wallet keys in the node).
We arevpreparing a big refactoring and there will be thorough documentation soon !

**Comment by AureliaDolo** [comment] 2022-01-03 08:47
> Do you have some kind of document describing software design?

@Vadiml1024 in massa-consensus there are pos.md and endorsement.md that cover the design of these specific parts. And in the wiki the concurrency file is a general (not so maintained) overview of how the different parts of the node are working together. But as @damip said that is expected to change quite soon

**Comment by damip** [comment] 2022-07-08 08:48
duplicate of https://github.com/massalabs/massa/issues/2719

**Closed by damip** 2022-07-08 08:48 UTC
Labels: bug, critical, refactoring, need spec
