### ISSUE TITLE
Be able to restart the network

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#3611] opened 2023-02-27 09:16 UTC
## Context

TDB

The goal is that in emergency case we can relaunch a network at a certain "snapshot".

We need to have the full state + ledger saved.

**Comment by Leo-Besancon** [comment] 2023-02-28 12:28
# Emergency Network restart

## Goals

As stated in the following issue: https://github.com/massalabs/massa/issues/3611

> The goal is that in emergency case we can relaunch a network at a certain "snapshot". We need to have the full state + ledger saved.

## Main tasks

- Define what should be included in a snapshot: TBD
    - Ledger
    - Full state:
        - Final
            > Final state from massa-final-state
        - Speculative?
            > ActiveHistory in massa-execution-worker?
            > Speculative ledger / executed-ops in massa-execution-worker?
- Expose a `create-snapshot Args` client command
    - Args may include, among others, `slot Slot`, `output_dir Path`
    - 
- Expose a `--from-snapshot Args` node launch argument.
    - Args may include, among others, `slot Slot`, `snapshot_dir Path`, `restart_timestamp MassaTime`
    - Replace existing ledger with snapshot ledger
    - 

## Nice to have for a better UX

Features for a better workflow:

- Have a dynamic `restart_timestamp` argument, e.g. being able to detect that a certain threshold of stakers want to restart **to the same snapshot** (basically, we could follow a similar pattern to what is used for the versioning module) -> E.g. Solana waits for 80% of validators to agree to a restart before activating it.
- Have the ability to query a snapshot from other nodes (what are the main differences with the bootstrap process? How so?)
    - For example, through a `query-snapshot snapshot_hash output_dir` client command.

To figure out further:

- Maybe have the ability to regularly make snapshots (similarly to backups)? Is that something we would like? Or are snapshots more likely made "on demand", when needed.
    - In the first case we may think about iterative snapshots, rolling snapshots, etc.
- Add gossiping warning messages to notify nodes of the emergency?
    - E.g. `WARN: N% of the total stake want a reboot.`
    - Question: what about banned peers in case of a fork of the network?
- Would we be able to edit a snapshot?
    - E.g. Just remove the rolls associated to an attacker, without rolling back the chain from a very early slot.

## Next steps

- Have discussions about these specs, make some decisions
- Create sub-issues and assign them

**Comment by Ben-PH** [comment] 2023-02-28 12:58
one pondering: after a restart, the bootstrap servers are going to be absolutely _flooded_. That might be something we need to consider as well.

**Comment by Leo-Besancon** [comment] 2023-03-01 10:45
Following the discussion with @AurelienFT and @Ben-PH, here are more precise specs
	
- Provide a way to create a snapshot behind a `create-snapshot` Rust feature. Most likely only our nodes would create a snapshot.
	This saves the snapshot data as an archive: Ledger + Final state (rolls, etc.)
- We provide this archive outside the network (that could be quite heavy, the leddger could be 1Tb).
- Some nodes, that want to "be here from the begining of the restart", would download the archive and run the node with `--from-snapshot Args` launch argument.
- Most nodes would just download a new software (if needed) without the snapshot archive, and bootstrap from our nodes once the network is up again.

Design choice:
- How do we handle the timestamps in that case?
	The problem is that the Slot timestamps would be desynced relative to the GENESIS_TIMESTAMP.
	To resolve this:
	- either we create a new `GENESIS_TIMESTAMP` entirely and include the ledger in the genesis blocks.
	- or we handle the delay through a `DELAY` const, effectively replacing `GENESIS_TIMESTAMP` by `GENESIS_TIMESTAMP + DELAY` whenever we make calculations based on this value.
	
	The first option is probably the easiest to develop initialy.

**Comment by AurelienFT** [comment] 2023-03-01 12:16
@damip having you thoughts on the différents solutions proposed above could be valuable

**Comment by Ben-PH** [comment] 2023-03-01 21:50
I think it can be done without editing the history of the network (a side-effect of changing the genesis timestamp, or adding a delay). It should be possible to keep the same genesis timestamp, no need to add a delay to the genesis.

It wouldn't be possible at the moment. Nodes are tightly coupled to a given timestamp purely by their period/thread tuple: genesis TS + (period * 16s) +  (0.5 * thread)

I propose we decouple the nodes from timestamps by making a slots "home timestamp" not a function of the slot-tuple, but a function of traversing the DAG of blocks, where each edge between nodes is coupled to a time-delta.

1. Obtain an initial timestamp. For period 0, this would be much the same as how it's done currently.
2. traverse the DAG, accumulating the time-deltas
3. [draw the rest of the owl](https://knowyourmeme.com/memes/how-to-draw-an-owl)
4. you have a blocks timestamp

In the network today, each edge would effectively be hard-coded accourding to the current genesis + (period * 16) + (thread * 0.5), but with a restart that would create, for example, a 1hr gap, it would just mean that the edges between the first block produced in the restarted network are worth 1hr instead of the usual 16s (+/- thread offset, of course).

This approach eliminates the need for down-stream changes to a previously locked-in state. This way, when a restart occurs, nothing about the network changes, except the next period takes longer, and once the period that had the different interval is old enough, it gets rolled up into the ledger just like what happens now anyway (with the added data that describes the "home timestamp" of the first nodes), and the fact that a restart happened is totally forgotten.

Decoupling a slot-number from a timestamp also allows other features, such as for initial vesting. Instead of having to choose a particular slot in advance, a timestamp can be chosen, and the slot can then be chosen according to which would be the ideal slot for the vesting block.

**Comment by damip** [comment] 2023-03-02 08:16
Indeed this is a complicated discussion with ramifications.

What should be dumped:
* the final state
* all kept consensus final blocks

What should happen on restart:
* load the dumped state
* reload the kept consensus final blocks
* recompute the smart contract cache
* the downtime should be handled as if it was misses, but:
  * without implicit roll sales
  * without crashing on missing PoS lookback or lack of cycle finalization (especially if the downtime spans multiple cycles)

**Comment by Ben-PH** [comment] 2023-03-02 09:04
> without crashing on missing PoS lookback or lack of cycle finalization (especially if the downtime spans multiple cycles)


If the system was already set up, such that the method to derive a slots timestamp was to traverse the DAG and accumulate the deltas, would it not make those concerns redundant? 

If concerns exist, and measures to address these concerns are downstream to the source (in other words, considered "after the fact"), it's in my nature to want to change the approach to address the concern directly. 

From my naive observation platform, decoupling a slot-tuple from a timestamp, and instead using an accumulation of the edges traversed to get from some sort of genesis-authority to a desired node/timestamp, could generalise the solution. This would, of course be a pain to implement, so the question would still remain: Would it be worth any value gained anyway?

**Comment by Ben-PH** [comment] 2023-03-02 10:07
if we use the time-delta approach to derive slot timestamps, the reboot process would specify a delta between the last pre-reboot period and the first post-reboot period to correspond with the time that we desire the rebooted network to commence.

That would prevent the issue of block misses arising to begin with, no?

**Comment by damip** [comment] 2023-03-02 17:00
I think we need to discuss this in a brainstorm. We can also not save the final blocks and have a new set of "genesis blocks" but whose period is greater than zero

**Comment by Leo-Besancon** [comment] 2023-03-06 11:17
We have discussed and decided on the following design choices.

**What data should we keep?**
- The ledger and the final state (that contains for instance rolls information)

**How do we ensure its consistancy?**
- Before Slot N is getting finalized, we should have the ledger at slot N-1, and the final state at slot N-1.
- When Slot N is getting finalized, we first dump the changes of the final state between N-1 and N, in a temporary folder.
- Then, we apply the changes to the ledger (this operation is atomic).
	- If it succeeds, we commit the final state's changes and we have a consistant snapshot at slot N.
	- If it fails, then the last consistant snapshot is at slot N-1.

**How do we handle the restart?**
We create a new network, reloading the final state and the ledger from the snapshot. However, we do not create a new "GENESIS_TIMESTAMP", we just add a "LAST_STARTED_PERIOD" in order to have the restart timestamp.

Then, we create new set of genesis blocks that start at LAST_STARTED_PERIOD. Indeed, we don't have potential "parents" for these first blocks after a restart.

This means that when we restart the network, the LAST_STARTED_PERIOD will be in the future. People will be able to bootstrap before the LAST_STARTED_PERIOD timestamp.

**What changes needs to be made to the codebase to allow this design?**
Remove the assumption that Genesis blocks are at period 0. This assumption is made in the consensus, protocole and pos modules (and may also be made elsewhere), and should be checked carefully.

**Comment by damip** [comment] 2023-03-06 12:43
@Leo-Besancon I took the freedom to edit your message. I agree with everything except the "How do we ensure its consistancy" part which I don't fully understand.

**Comment by Leo-Besancon** [comment] 2023-03-06 12:50
@damip Ok, thank you for clarifying some sentences.

The "How do we ensure its consistancy" part is IMO an implementation detail, I can propose a draft and we'll see if that makes sense. Basically, it's to avoid issues about rolling back a part of the state if we fail somewhere else. I propose to commit changes in a two step process to always be able to get the get a consistant final state.

**Comment by Ben-PH** [comment] 2023-03-06 14:00
I don't see any particular advantage to the time-delta approach over the "LAST_START_PERIOD" here. I've opened a discussion about the more general topic of the decoupling in #3647.

**Comment by Ben-PH** [comment] 2023-03-16 14:04
Something that came to mind: We could generalise the concept of genesis period, and given that each period is just an offset from an arbitrary moment in time, why not do the following:

- We can do away with a genesis timestamp entirely, and just go by the standard 1970 epock
- whenever you start a network, the period number is just what it would be as if the network started on said epoch.
- Brand new networks, and rebooted networks, are essentially the same, only that rebooted networks have  start with an initial state.

This would mean `LAST_START_PERIOD` would become `GENESIS_PERIOD`. All timestamp calculations would be period * interval, with no requirement for what is currently the genesis timestamp.

I'm writing this under the assumption that, once we have a final state, the network has no care for what things were like before that. All that matters is the state of the system, not how it got there, and anything before the final state is redundant.

**Comment by Leo-Besancon** [comment] 2023-03-17 12:19
Following up on a discussion with @damip, aside from testing the current PR, I will try and improve the current code with the following features:
- Read/Write the final_state in RocksDB instead of files ( create a new table in the current RocksDB instance used for the ledger)
- Unify the concepts of "Genesis" and "Snapshot" networks (this is closely related to the latest message of @Ben-PH ).
- Be able to bootstrap from a restarted network without downloading new software (essentially, this means that we should bootstrap the LAST_START_PERIOD value that is currently a constant in the code).

As a follow-up, we will think about how to handle backups of the snapshot, in case we have to restart the network from an earlier slot than what was last written. See if RocksDB can handle customizable backups of the DB.

**Comment by Leo-Besancon** [comment] 2023-03-29 14:16
A review of the current linked PR with @damip lead to the following decisions (please don't hesitate to add details to make sure we are on the same page!):

What has to be done for inclusion in testnet_21:

- Assume the whole FinalState is on disk, similarly to the ledger (even if it will not be the case at first). Revert to initial config data for now instead of loading it from the disk.
- Interpolate the initial_state if we restart from a snapshot to handle the downtime
    - Instead of creating a new "state", we "plug in the holes" by, for instance, repeating the last known cycle)
    - This means no bootstraping of the initial state (initial_rolls / initial_seeds / initial state hash) is needed
	
As a follow-up:

- Serialize the final state **changes** on disk, in the same way we handle ledger changes.
    - Incrementaly, we only want to serialize the changes
    - But consolidate the final_state at each step with an apply_change (that e.g. will remove un-needed keys)
    - For this, we need to build a Key for each change based on its ID (e.g. operation_id)
 - Unify Genesis and Snapshot
     - Unify "new" and "from_snapshot" methods
     - Created a "default" ledger based on config files.
 - Think about how to handle backups of the snapshot
     - In case we have to restart the network from an earlier slot than what was last written. 
     - See if RocksDB can handle customizable backups of the DB.

**Comment by Leo-Besancon** [comment] 2023-04-17 08:24
So I implemented the RocksDB writes for AsyncPool messages. We'll probably need to go over what I've done this week.
Everything seems to be working, except for some CI tests that use a low T0 value (100ms). This prompted me to log the times. During the tests::scenarios_mandatories::test_readonly_execution, settle_slot for async_pool clocked at 100µs +/- 50µs on my PR, while it is 2µs +/- 1µs on testnet21.

We'll see if we can optimize this, and if it is a problem (keep in mind, these times are queried **not** under load).

**Comment by Leo-Besancon** [comment] 2023-05-03 09:28
# Network restart documentation

## Goals of the network restart
If the blockchain crashes (corrupted / attacked ledger, all nodes crash, etc.) and we want to keep the same main parameters of the network (same `GENESIS_TIMESTAMP`, same ledger, same final_state, etc.), then we can restart the network.
	
ONE node should restart from a snapshot (which is just the RocksDB ledger, read as usual), and the other nodes should bootstrap from it.
	
## Command line

```sh 
cargo run --release -- --restart-from-snapshot-at-period 200
```

Means: the node will restart from the ledger and final_state on disk (usual path in the config). Block production will start once the period given in args is reached (here, 200).
		
## Scenario

1. At period 40, the network crashes.
2. We restart one node N0, at the time of period 80, with `cargo run --release -- --restart-from-snapshot-at-period 200`
3. We start one other node N1, at the time of period 100, with `cargo run --release`
4. The node N1 will bootstrap from N0. No blocks are produced yet.
5. At the time of period 200, block production starts again.
		
## Current codebase

The final state (async_pool, executed_ops, deferred_credits, roll_counts, etc.) **IS NOT SAVED ON DISK!**
This means only the ledger currently persists during a network restart.
		
## Additional notes
	
###	Why is block production delayed?

In order to give time to all nodes to rejoin the network after a crash and bootstrap. If we don't give them the time, their rolls would be sold because most stakers would have a lot of block miss.
		
###	In sandbox

Sandbox feature can be enabled. For instance, here is a test scenario:

1. Run the node as usual: `cargo run --release --features sandbox`
2. Make transaction, buy rolls, etc.
3. Shut down the node at slot S_0.
4. Restart the network: `cargo run --release --features sandbox --restart-from-snapshot-at-period S_1`

Here, the network will restart, and the network will start producing blocks again 10 seconds after launch.

**/!\ This means that the genesis timestamp will be different between runs, but it should not matter in most cases.**

###	Backups

By default, the network restarts from the state associated with the last final slot before the shutdown.
However, we may sometimes want to recover from an earlier state (e.g. if an attacker stole 50% of all Massa, we want to restart with the state before the attack.
We use RocksDB checkpoint system to save the state at regular interval (see the `PERIODS_BETWEEN_BACKUPS constant` in `massa > massa-models > src > config > constants.rs`)
Backups for `Slot {period, thread}` are stored in `massa > massa-node > storage > ledger > rocks_db_backup > backup_[period]_[thread]`
Backups are hard links of the rocks_db, so the overhead of storing them should be minimal.
To recover from a backup, simply replace the contents of the rocks_db folder by the contents of the target backup folder.

**Comment by damip** [comment] 2023-05-03 10:24
Nice @Leo-Besancon  ! Can you add it to the dev docs https://massalabs.github.io/massa/massa_node/ so that it doesn't get lost with this issue ?

**Closed** 2023-06-01 08:16 UTC
