### ISSUE TITLE
panicked at 'assertion failed

### ISSUE THREAD

**Issue by chriscooper1983** [massalabs/massa#3337] opened 2022-12-19 11:51 UTC
```
    Finished release [optimized] target(s) in 0.42s
     Running `/root/massa/target/release/massa-node -p 123`
ESC[2m2022-12-19T11:47:19.853421ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_nodeESC[0mESC[2m:ESC[0m Node version : TEST.17.2
ESC[2m2022-12-19T11:47:19.917884ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m Start bootstrapping from 149.202.89.125:31245
ESC[2m2022-12-19T11:47:23.445657ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m State bootstrap complete
ESC[2m2022-12-19T11:47:23.483584ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_bootstrap::clientESC[0mESC[2m:ESC[0m Successful bootstrap
ESC[2m2022-12-19T11:47:23.484199ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_network_workerESC[0mESC[2m:ESC[0m The node_id of this node is: P12jrXPtaZPMBAbmzYd9WdZCMvgCv53Kwa5CadW1ZvRKCcy175h
ESC[2m2022-12-19T11:47:23.507910ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_consensus_worker::worker::initESC[0mESC[2m:ESC[0m Started node at time 2022-12-19T11:47:23Z, cycle 780, period 99852, thread 22
ESC[2m2022-12-19T11:47:23.544000ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_protocol_worker::protocol_networkESC[0mESC[2m:ESC[0m Connected to node P122Xr6CVGHx9iPR9NZZF1sqTUR7mJ1tTX1A7pDrMKyv6eYTEarB
ESC[2m2022-12-19T11:47:23.544571ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_protocol_worker::protocol_networkESC[0mESC[2m:ESC[0m Connected to node P1z6xG26ikEd26KWZPuqnW8gwu6noCgbutn6jUi1wGTXwrHorRV
ESC[2m2022-12-19T11:47:23.689938ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_protocol_worker::protocol_networkESC[0mESC[2m:ESC[0m Connected to node P1KHKMLQZ9jed32FWgEirdhjeqKWQGfupWVLYNgZDKhoLioDCKx
ESC[2m2022-12-19T11:47:23.743256ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_protocol_worker::protocol_networkESC[0mESC[2m:ESC[0m Connected to node P1A7GZYZ5FuvHdS9uQupk3StDxVxwbPqd4vgMDupmqmazM1cGBN
ESC[2m2022-12-19T11:47:24.103214ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_protocol_worker::protocol_networkESC[0mESC[2m:ESC[0m Connected to node P12FmABKTRd5kFK6fjSSYes3hSFq3TcSbjLTcHjba83MkRRFnUUr
ESC[2m2022-12-19T11:47:26.457313ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_final_state::final_stateESC[0mESC[2m:ESC[0m final_state hash at slot (period: 99850, thread: 15): 2uY2P5FVfvdDZdagkAeiKU2epCXqV9VeCr4PRrUng1RWpcy7Ty
ESC[2m2022-12-19T11:47:26.458581ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_final_state::final_stateESC[0mESC[2m:ESC[0m final_state hash at slot (period: 99850, thread: 16): H5VqtjmiSabsWP1Y6dTgPEbAaTdaiKfiXvJcvxhrpxBZEenq3
ESC[2m2022-12-19T11:47:26.459594ZESC[0m ESC[32m INFOESC[0m ESC[2mmassa_final_state::final_stateESC[0mESC[2m:ESC[0m final_state hash at slot (period: 99850, thread: 17): GmpDtqEbGZr6A88MNfVQM152fa8MxkWnWGyGLF3xGWrHzKV7T
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM0`,
 right: `XMM0`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_x64.rs:1421:40
stack backtrace:
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM3`,
 right: `XMM3`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_x64.rs:1435:40
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM3`,
 right: `XMM3`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_x64.rs:1624:40
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `XMM3`,
 right: `XMM3`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_x64.rs:1463:40
   0:     0x5596b9502260 - std::backtrace_rs::backtrace::libunwind::trace::he4d5f2c13fd7ea58
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5596b9502260 - std::backtrace_rs::backtrace::trace_unsynchronized::ha872462b0d7f1993
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5596b9502260 - std::sys_common::backtrace::_print_fmt::hfa57ea34975e92c8
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5596b9502260 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf4fb6a2aa638ae6
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5596b952682e - core::fmt::write::h556296da8255a0fe
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/core/src/fmt/mod.rs:1209:17
   5:     0x5596b94fcac5 - std::io::Write::write_fmt::h1e63bc45d9e0b177
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/io/mod.rs:1682:15
   6:     0x5596b9502025 - std::sys_common::backtrace::_print::h18ecb2198a8971d0
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5596b9502025 - std::sys_common::backtrace::print::he62f784f6f099fe2
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5596b9503bdf - std::panicking::default_hook::{{closure}}::h220c4bc545c14f7e
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:267:22
   9:     0x5596b950391a - std::panicking::default_hook::hc6a46490400a51ce
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:286:9
  10:     0x5596b872b51e - massa_node::run::{{closure}}::{{closure}}::h859793957d960adc
  11:     0x5596b95042fd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hba54d23f8fd826e2
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2032:9
  12:     0x5596b95042fd - std::panicking::rust_panic_with_hook::hec8b21fa74280350
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:692:13
  13:     0x5596b9504077 - std::panicking::begin_panic_handler::{{closure}}::hfc7a6bbbe087d67f
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:579:13
  14:     0x5596b950270c - std::sys_common::backtrace::__rust_end_short_backtrace::h9522cd483b462760
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x5596b9503d92 - rust_begin_unwind
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:575:5
  16:     0x5596b8569d03 - core::panicking::panic_fmt::hed336b84331644c6
17:     0x5596b9523e7b - core::panicking::assert_failed_inner::h35d320f7e516fb8e
  18:     0x5596b8524b7b - core::panicking::assert_failed::hccf82c78a8317c03
  19:     0x5596b8e240a9 - <wasmer_compiler_singlepass::machine_x64::AssemblerX64 as wasmer_compiler_singlepass::emitter_x64::EmitterX64>::emit_vaddsd::h1e1b2c776f06cf3a
  20:     0x5596b8e6ff2a - <wasmer_compiler_singlepass::machine_x64::MachineX86_64 as wasmer_compiler_singlepass::machine::Machine>::convert_f64_i64::h2da1f6df6e9fc25f
  21:     0x5596b8df8aaf - wasmer_compiler_singlepass::codegen::FuncGen<M>::feed_operator::h14392320c3f9b696
  22:     0x5596b8e7fe8d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hd8797959f3689c6a
  23:     0x5596b8ebc44c - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h67365c9fa4787cf0
  24:     0x5596b8da58c2 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h8856a4b6243158f7
  25:     0x5596b8e87f1a - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  26:     0x5596b8ec331b - rayon_core::job::StackJob<L,F,R>::run_inline::h8cc6113136394d0f
  27:     0x5596b8e7a795 - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  28:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  29:     0x5596b8ec331b - rayon_core::job::StackJob<L,F,R>::run_inline::h8cc6113136394d0f
  30:     0x5596b8e7a795 - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  31:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  32:     0x5596b8e7a5cf - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  33:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  34:     0x5596b8e7a5cf - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  35:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  36:     0x5596b8ec598b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h47e03439ad078719
  37:     0x5596b8527f84 - rayon_core::registry::WorkerThread::wait_until_cold::h4395542c149e5ceb
  38:     0x5596b8f09bdf - rayon_core::registry::ThreadBuilder::run::h5308451a2c83133e
  39:     0x5596b8f083fa - std::sys_common::backtrace::__rust_begin_short_backtrace::h04d729e6b468fc93
  40:     0x5596b8f0c46b - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcde95657e64c95e5
  41:     0x5596b95072d3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb9beccc25c64a001
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2000:9
  42:     0x5596b95072d3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hde98428e87ac1a81
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2000:9
  43:     0x5596b95072d3 - std::sys::unix::thread::Thread::new::thread_start::h2ef156d73deb51c1
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7f6bcc808ea7 - start_thread
  45:     0x7f6bcc5dca2f - clone
  46:                0x0 - <unknown>
stack backtrace:
   0:     0x5596b9502260 - std::backtrace_rs::backtrace::libunwind::trace::he4d5f2c13fd7ea58
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5596b9502260 - std::backtrace_rs::backtrace::trace_unsynchronized::ha872462b0d7f1993
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5596b9502260 - std::sys_common::backtrace::_print_fmt::hfa57ea34975e92c8
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5596b9502260 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf4fb6a2aa638ae6
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5596b952682e - core::fmt::write::h556296da8255a0fe
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/core/src/fmt/mod.rs:1209:17
   5:     0x5596b94fcac5 - std::io::Write::write_fmt::h1e63bc45d9e0b177
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/io/mod.rs:1682:15
   6:     0x5596b9502025 - std::sys_common::backtrace::_print::h18ecb2198a8971d0
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5596b9502025 - std::sys_common::backtrace::print::he62f784f6f099fe2
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5596b9503bdf - std::panicking::default_hook::{{closure}}::h220c4bc545c14f7e
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:267:22
   9:     0x5596b950391a - std::panicking::default_hook::hc6a46490400a51ce
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:286:9
  10:     0x5596b872b51e - massa_node::run::{{closure}}::{{closure}}::h859793957d960adc
  11:     0x5596b95042fd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hba54d23f8fd826e2
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/alloc/src/boxed.rs:2032:9
  12:     0x5596b95042fd - std::panicking::rust_panic_with_hook::hec8b21fa74280350
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:692:13
  13:     0x5596b9504077 - std::panicking::begin_panic_handler::{{closure}}::hfc7a6bbbe087d67f
 14:     0x5596b950270c - std::sys_common::backtrace::__rust_end_short_backtrace::h9522cd483b462760
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x5596b9503d92 - rust_begin_unwind
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/std/src/panicking.rs:575:5
  16:     0x5596b8569d03 - core::panicking::panic_fmt::hed336b84331644c6
                               at /rustc/e631891f7ad40eac3ef58ec3c2b57ecd81e40615/library/core/src/panicking.rs:65:14
  17:     0x5596b9523e7b - core::panicking::assert_failed_inner::h35d320f7e516fb8e
  18:     0x5596b8524b7b - core::panicking::assert_failed::hccf82c78a8317c03
  19:     0x5596b8e25729 - <wasmer_compiler_singlepass::machine_x64::AssemblerX64 as wasmer_compiler_singlepass::emitter_x64::EmitterX64>::emit_vsubsd::h14525666e7f17a92
  20:     0x5596b8e40eb1 - wasmer_compiler_singlepass::machine_x64::MachineX86_64::emit_relaxed_avx::h4afe03943bbeb422
  21:     0x5596b8dfdfe9 - wasmer_compiler_singlepass::codegen::FuncGen<M>::feed_operator::h14392320c3f9b696
  22:     0x5596b8e7fe8d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hd8797959f3689c6a
  23:     0x5596b8ebc44c - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h67365c9fa4787cf0
  24:     0x5596b8da58c2 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h8856a4b6243158f7
  25:     0x5596b8e87f1a - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  26:     0x5596b8e7a5cf - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  27:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  28:     0x5596b8e7a5cf - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  29:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  30:     0x5596b8ec598b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h47e03439ad078719
  31:     0x5596b8527f84 - rayon_core::registry::WorkerThread::wait_until_cold::h4395542c149e5ceb
  32:     0x5596b8e7a690 - rayon_core::registry::in_worker::h33a706fadcf2fb6b
  33:     0x5596b8e88016 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf4f525ee6ed4e195
  34:     0x5596b8ec598b - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::
  ```

**Comment by AurelienFT** [comment] 2022-12-19 12:45
Hello,
Thanks for the reporting.
This is a duplicate of #3326 and so I will close it to keep one version of the issue. You can follow our advancement and comment in #3326

**Closed by AurelienFT** 2022-12-19 12:45 UTC
