### ISSUE TITLE
realloc(): invalid old size

### ISSUE THREAD

**Issue by damip** [massalabs/massa#2284] opened 2022-02-13 11:31 UTC
```
2022-02-13T04:51:15.048733Z  INFO massa_protocol_worker::protocol_worker: Connected to node 8AD4WgWLPoKzztmiUjFn2t7oDs6iitXvEBPNpYWHKTdD8ziykw
realloc(): invalid old size
```

And then the node crashes abruptly (no more messages)

**Comment by damip** [comment] 2022-02-15 13:41
@massalabs/core-team  any ideas ? unfortunately I have no more info

**Comment by AureliaDolo** [comment] 2022-02-16 08:31
> You get an invalid old size error when your code writes the memory that malloc/realloc allocated for "housekeeping information". This is where they store the "old" allocated size. This also happens when the pointer that you pass to realloc has not been properly initialized, i.e. it's neither a NULL nor a pointer previously returned from malloc/calloc/realloc.

https://stackoverflow.com/questions/24579698/realloc-invalid-old-size

**Comment by adrien-zinger** [comment] 2022-02-23 10:36
It can be in `wasmer` or also in another big library that like to play with our stack as `tokio`. That's a pity that we lack information here.

In cautious bassoon, we don't play with the program memory outside the vm. I think, if the problem happened while executing a smart contract, that the problem is deeper.

I've investigated in the tokio and wasmer repositories with no results. But the more probable explanation is that the user has had an _Out Of Memory_.

In any case, I would close the issue because of the lack of information and the impossibility to reproduce.

**Closed** 2022-02-23 10:40 UTC
Labels: bug
