### ISSUE TITLE
Failed bootstraps

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa#2723] opened 2022-06-22 09:33 UTC
Bootstrap fails, then bootstrap succeeds but with weird behavior, speculative execution cache empty, send queue fulll, etc

[failed_bootstraps_logs.txt](https://github.com/massalabs/massa/files/8956335/failed_bootstraps_logs.txt)

**Comment by damip** [comment] 2022-06-22 09:40
Duplicate of https://github.com/massalabs/massa/issues/2722

**Comment by AurelienFT** [comment] 2022-07-04 07:30
Close in favor #2722

**Closed by AurelienFT** 2022-07-04 07:30 UTC
Labels: bug
