### ISSUE TITLE
Weird stuff in the logs

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#2816] opened 2022-07-15 17:14 UTC
There are some weird things that appear in the logs. Probably someone playing with SCs. Don't know how it ended up here!

```
Error: Invalid index. at src/contracts/order.ts:210 col: 5
Error: Invalid index. at src/contracts/order.ts:210 col: 5
Error: Invalid index. at src/contracts/order.ts:210 col: 5
2022-07-15T14:25:36.002201Z  INFO massa_consensus_worker::consensus_worker: Started cycle 282
2022-07-15T14:25:45.600651Z  INFO massa_protocol_worker::protocol_worker: Connection closed with P1P66qusenUtpKNW3zd4hny7NbWVzNNZxG5irdAGLKQDWX2QNmR
2022-07-15T14:25:46.249219Z  INFO massa_protocol_worker::protocol_worker: Connected to node P12YndMuDgBiXArjmGU4u6FYvRVvVUTgDXU9KrxKdt3XneVyVRFz
2022-07-15T14:25:56.163434Z  INFO massa_protocol_worker::protocol_worker: Connected to node P14qRSBVstXDF92euPMCTuKtKGbY3JNj7yVXh4b1ff2BGmHjZg5
2022-07-15T14:26:06.751586Z  INFO massa_protocol_worker::protocol_worker: Connected to node P1My72YP2nr9ie1hLm4BCSFqXeqtbnQjxJcmsa4EEEG1f3ZP8zP
Error: Invalid index. at src/contracts/order.ts:210 col: 5
Error: Index out of range at ~lib/array.ts:114 col: 42
Error: Index out of range at ~lib/array.ts:114 col: 42
Error: Index out of range at ~lib/array.ts:114 col: 42
Error: Index out of range at ~lib/array.ts:114 col: 42
```

**Comment by damip** [comment] 2022-07-15 23:20
duplicate of https://github.com/massalabs/massa/issues/2811

**Closed** 2022-08-02 08:29 UTC
Labels: logging
