### ISSUE TITLE
Operation timestamp feature

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa#3207] opened 2022-11-04 13:53 UTC
**Is your feature request related to a problem? Please describe.**
There is no way at the moment to understand when an Operation has been initiated. From an end-user perspective (block explorer users specifically), the ability to prove when the operation has been initiated by the user is very important for several reasons: tax reporting purposes, proving the payment to another user, etc. Usually it is called a timestamp of a transaction on other blockchains.

User story:
As an operation sender, I want to be able to see the date and time when I executed it, in order to prove I sent it at a certain moment. 

**Describe the solution you'd like**
I'd like this information to be accessible in Node's API, specifically in the operations endpoint.

**Describe alternatives you've considered**
Maybe possible to do by slot (period, thread) but that means that we record the processing time, which in my understanding can differ from the execution time for quite some time (days even, no?)

**Additional context**
n/A

**Comment by damip** [comment] 2022-11-07 07:54
duplicate of https://github.com/massalabs/massa/issues/3200

**Comment by AurelienFT** [comment] 2022-11-23 19:46
Close in favor of #3200

**Closed by AurelienFT** 2022-11-23 19:46 UTC
