### ISSUE TITLE
testnet0 crashed after API call

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa#3257] opened 2022-11-26 13:50 UTC
```
2022-11-26T13:12:45.547099Z DEBUG massa_network_worker::network_worker: connection closed connection_id=1432164, ip=198.27.74.5, reason=Failed
2022-11-26T13:12:45.549851Z DEBUG massa_network_worker::network_worker: connection closed connection_id=1432165, ip=158.69.23.120, reason=Failed
thread 'tokio-node-14' panicked at 'Expected always-serializable type; qed: Error("key must be a string", line: 0, column: 0)', massa-api/src/lib.rs:150:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

full log available on the home directory

**Comment by damip** [comment] 2022-11-26 14:40
> ```
> 2022-11-26T13:12:45.547099Z DEBUG massa_network_worker::network_worker: connection closed connection_id=1432164, ip=198.27.74.5, reason=Failed
> 2022-11-26T13:12:45.549851Z DEBUG massa_network_worker::network_worker: connection closed connection_id=1432165, ip=158.69.23.120, reason=Failed
> thread 'tokio-node-14' panicked at 'Expected always-serializable type; qed: Error("key must be a string", line: 0, column: 0)', massa-api/src/lib.rs:150:1
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> full log available on the home directory

What was the API call ?

**Comment by aoudiamoncef** [comment] 2022-11-26 20:13
Similar to https://github.com/paritytech/cumulus/issues/1224 and https://github.com/paritytech/substrate/issues/4641

**Comment by AurelienFT** [comment] 2022-11-27 22:35
Note: this was on TEST.16

**Comment by aoudiamoncef** [comment] 2022-11-27 23:13
We have similar issues in both `jsonrpc` and `jsonrpsee` crates, so even in `testnet17`we could have it.

**Comment by AurelienFT** [comment] 2022-11-28 22:45
I have successfully reproduced it in the `get_operations` endpoint. First of all you create an operation with a operation datastore (for example here is the serialized content I used) : 
```
[
    0, 246, 154,   9,   3, 192, 154,  12,   0, 163,  22,   0,
   97, 115, 109,   1,   0,   0,   0,   1,  49,   9,  96,   2,
  127, 127,   0,  96,   1, 127,   1, 127,  96,   0,   0,  96,
    2, 127, 127,   1, 127,  96,   1, 127,   0,  96,   3, 127,
  127, 127,   1, 127,  96,   3, 127, 127, 127,   0,  96,   4,
  127, 127, 127, 127,   0,  96,   2, 127, 126,   0,   2, 122,
    4,   3, 101, 110, 118,   5,  97,  98, 111, 114, 116,   0,
    7,   5, 109,  97, 115, 115,  97,  27,  97, 115, 115, 101,
  109,  98, 108, 121,  95, 115,  99, 114, 105, 112, 116,  95,
  103, 101, 116,  95, 111, 112,  95, 100,  97, 116,  97,   0,
    1,   5, 109,  97, 115, 115,  97,  25,  97, 115, 115, 101,
  109,  98, 108, 121,  95, 115,  99, 114, 105, 112, 116,  95,
   99, 114, 101,  97, 116, 101,  95, 115,  99,   0,   1,   5,
  109,  97, 115, 115,  97,  30,  97, 115, 115, 101, 109,  98,
  108, 121,  95, 115,  99, 114, 105, 112, 116,  95, 103, 101,
  110, 101, 114,  97, 116, 101,  95, 101, 118, 101, 110, 116,
    0,   4,   3,  47,  46,   4,   0,   1,   0,   0,   0,   0,
    3,   6,   0,   0,   0,   5,   3,   1,   0,   3,   6,   8,
    3,   3,   3,   2,   2,   2,   2,   2,   2,   2,   5,   1,
    0,   0,   5,   1,   1,   1,   1,   3,   3,   4,   2,   1,
    4,   2,   2,   4,   5,   1, 112,   1,   1,   1,   5,   3,
    1,   0,   1,   6, 124,  22, 127,   0,  65,   0,  11, 127,
    0,  65,   1,  11, 127,   0,  65,   2,  11, 127,   1,  65,
    0,  11, 127,   1,  65,   0,  11, 127,   0,  65,   0,  11,
  127,   1,  65,   0,  11, 127,   1,  65,   0,  11, 127,   0,
   65, 208,   3,  11, 127,   0,  65, 240,   3,  11, 127,   0,
   65, 160,   4,  11, 127,   0,  65, 208,   4,  11, 127,   0,
   65, 128,   5,  11, 127,   0,  65, 176,   5,  11, 127,   0,
   65, 208,   5,  11, 126,   0,  66,   0,  11, 127,   0,  65,
  128,   6,  11, 127,   0,  65, 176,   6,  11, 127,   0,  65,
  208,   6,  11, 127,   0,  65, 240,   6,  11, 127,   0,  65,
  128,   8,  11, 127,   0,  65, 196,   8,  11,   7,  69,   7,
    4, 109,  97, 105, 110,   0,  45,   5,  95,  95, 110, 101,
  119,   0,  11,   5,  95,  95, 112, 105, 110,   0,  46,   7,
   95,  95, 117, 110, 112, 105, 110,   0,  47,   9,  95,  95,
   99, 111, 108, 108, 101,  99, 116,   0,  48,  11,  95,  95,
  114, 116, 116, 105,  95,  98,  97, 115, 101,   3,  20,   6,
  109, 101, 109, 111, 114, 121,   2,   0,   8,   1,  49,   9,
    6,   1,   0,  65,   1,  11,   0,  12,   1,  22,  10, 159,
    9,  46,  96,   1,   5, 127,  63,   0,  33,   1,  32,   1,
   65,  16, 116,  65,  15, 106,  65,  15,  65, 127, 115, 113,
   33,   2,  32,   0,  32,   2,  75,   4,  64,  32,   0,  32,
    2, 107,  65, 255, 255,   3, 106,  65, 255, 255,   3,  65,
  127, 115, 113,  65,  16, 118,  33,   3,  32,   1,  34,   4,
   32,   3,  34,   5,  32,   4,  32,   5,  74,  27,  33,   4,
   32,   4,  64,   0,  65,   0,  72,   4,  64,  32,   3,  64,
    0,  65,   0,  72,   4,  64,   0,  11,  11,  11,  32,   0,
   36,   4,  11,   9,   0,  32,   0,  32,   1,  54,   2,   0,
   11,  81,   1,   4, 127,  32,   0,  65, 252, 255, 255, 255,
    3,  75,   4,  64,  65, 144,   1,  65, 208,   1,  65,  33,
   65,  29,  16,   0,   0,  11,  35,   4,  33,   1,  35,   4,
   65,   4, 106,  33,   2,   2, 127,  32,   0,  33,   3,  32,
    3,  65,   4, 106,  65,  15, 106,  65,  15,  65, 127, 115,
  113,  65,   4, 107,  11,  33,   4,  32,   2,  32,   4, 106,
   16,   4,  32,   1,  32,   4,  16,   5,  32,   2,  11,   9,
    0,  32,   0,  32,   1,  54,   2,   4,  11,   9,   0,  32,
    0,  32,   1,  54,   2,   8,  11,   9,   0,  32,   0,  32,
    1,  54,   2,  12,  11,   9,   0,  32,   0,  32,   1,  54,
    2,  16,  11,  75,   1,   2, 127,  32,   0,  65, 236, 255,
  255, 255,   3,  75,   4,  64,  65, 144,   1,  65, 208,   1,
   65, 214,   0,  65,  30,  16,   0,   0,  11,  65,  16,  32,
    0, 106,  16,   6,  33,   2,  32,   2,  65,   4, 107,  33,
    3,  32,   3,  65,   0,  16,   7,  32,   3,  65,   0,  16,
    8,  32,   3,  32,   1,  16,   9,  32,   3,  32,   0,  16,
   10,  32,   2,  65,  16, 106,  11,   3,   0,   1,  11,  17,
    0,  32,   0,  32,   1,  54,   2,   0,  32,   0,  32,   1,
   65,   0,  16,  12,  11,   9,   0,  32,   0,  32,   1,  54,
    2,   4,  11,   9,   0,  32,   0,  32,   1,  54,   2,   8,
   11, 111,   1,   1, 127,  32,   0,  69,   4,  64,  65,  12,
   65,   2,  16,  11,  33,   0,  11,  32,   0,  65,   0,  16,
   13,  32,   0,  65,   0,  16,  14,  32,   0,  65,   0,  16,
   15,  32,   1,  65, 252, 255, 255, 255,   3,  32,   2, 118,
   75,   4,  64,  65,  32,  65, 208,   0,  65,  19,  65,  57,
   16,   0,   0,  11,  32,   1,  32,   2, 116,  34,   1,  65,
    0,  16,  11,  33,   3,  65,   0,  35,   2,  71,  26,  32,
    3,  65,   0,  32,   1, 252,  11,   0,  32,   0,  32,   3,
   16,  13,  32,   0,  32,   3,  16,  14,  32,   0,  32,   1,
   16,  15,  32,   0,  11,  28,   0,  32,   0,  69,   4,  64,
   65,  12,  65,   4,  16,  11,  33,   0,  11,  32,   0,  32,
    1,  65,   0,  16,  16,  33,   0,  32,   0,  11,  13,   0,
   32,   0,  65,  20, 107,  40,   2,  16,  65,   0, 118,  11,
   17,   0,  32,   0,  32,   1,  54,   2,   8,  32,   0,  32,
    1,  65,   0,  16,  12,  11,  46,   1,   1, 127,  32,   1,
   32,   0,  16,  18,  79,   4,  64,  65, 144,   2,  65, 208,
    2,  65, 206,   0,  65,  41,  16,   0,   0,  11,  32,   0,
   32,   1,  65,   0, 116, 106,  45,   0,   0,  33,   2,  65,
    0,  26,  32,   2,  11,  40,   0,  32,   1,  32,   0,  40,
    2,   8,  79,   4,  64,  65, 144,   2,  65, 144,   3,  65,
  178,   1,  65,  45,  16,   0,   0,  11,  32,   0,  40,   2,
    4,  32,   1, 106,  32,   2,  58,   0,   0,  11,   9,   0,
   32,   0,  32,   1,  55,   3,   0,  11,  99,   1,   2, 127,
   32,   0,  69,   4,  64,  65,  12,  65,   3,  16,  11,  33,
    0,  11,  32,   0,  66,   0,  16,  22,  32,   0,  65,   0,
   65,   0,  16,  17,  16,  19,  32,   0,  65,   0,  32,   1,
   16,  18,  16,  17,  16,  19,  65,   0,  33,   2,   2,  64,
    3,  64,  32,   2,  32,   1,  16,  18,  72,  33,   3,  32,
    3,   4,  64,   2,  64,  32,   0,  40,   2,   8,  32,   2,
   32,   1,  32,   2,  16,  20,  16,  21,  11,  32,   2,  65,
    1, 106,  33,   2,  12,   1,  11,  11,  11,  32,   0,  11,
   63,   1,   2, 127,  32,   1,  65, 252, 255, 255, 255,   3,
   65,   0, 118,  75,   4,  64,  65,  32,  65, 208,   2,  65,
   51,  65,  60,  16,   0,   0,  11,  32,   1,  65,   0, 116,
   33,   2,  32,   2,  65,   5,  16,  11,  33,   3,  65,   0,
   35,   2,  71,  26,  32,   3,  65,   0,  32,   2, 252,  11,
    0,  32,   3,  11,  33,   0,   2,  64,   2,  64,   2,  64,
   35,   6,  14,   2,   1,   2,   0,  11,   0,  11,  65,   0,
   65,   0,  16,  24,  33,   1,  11,  32,   0,  32,   1,  16,
   23,  11,  37,   0,  35,  21,  65,   4, 106,  65,  15, 106,
   65,  15,  65, 127, 115, 113,  65,   4, 107,  36,   3,  35,
    3,  36,   4,  65,   0,  65,   0,  36,   6,  65,   0,  16,
   25,  36,   7,  11,   4,   0,  16,  26,  11,   4,   0,  16,
   27,  11,   4,   0,  16,  28,  11,   4,   0,  16,  29,  11,
    4,   0,  16,  30,  11,   4,   0,  16,  31,  11,  29,   1,
    1, 127,  32,   0,  32,   1,  16,  11,  33,   3,  32,   2,
    4,  64,  32,   3,  32,   2,  32,   0, 252,  10,   0,   0,
   11,  32,   3,  11,   6,   0,  32,   0,  16,   1,  11,  17,
    0,  32,   0,  32,   1,  54,   2,   0,  32,   0,  32,   1,
   65,   0,  16,  12,  11,   9,   0,  32,   0,  32,   1,  58,
    0,   4,  11,  42,   0,  32,   0,  69,   4,  64,  65,   5,
   65,   6,  16,  11,  33,   0,  11,  32,   0,  65,   0,  16,
   35,  32,   0,  65,   0,  16,  36,  32,   0,  32,   1,  16,
   35,  32,   0,  32,   2,  16,  36,  32,   0,  11,  10,   0,
   65,   0,  32,   0,  65,   1,  16,  37,  11,   8,   0,  32,
    0,  16,   2,  16,  38,  11,   7,   0,  32,   0,  40,   2,
    0,  11,  13,   0,  32,   0,  65,  20, 107,  40,   2,  16,
   65,   1, 118,  11,  74,   1,   4, 127,  32,   0,  16,  41,
   65,   1, 116,  33,   2,  32,   1,  16,  41,  65,   1, 116,
   33,   3,  32,   2,  32,   3, 106,  33,   4,  32,   4,  65,
    0,  70,   4,  64,  65, 240,   7,  15,  11,  32,   4,  65,
    1,  16,  11,  33,   5,  32,   5,  32,   0,  32,   2, 252,
   10,   0,   0,  32,   5,  32,   2, 106,  32,   1,  32,   3,
  252,  10,   0,   0,  32,   5,  11,   8,   0,  32,   0,  32,
    1,  16,  42,  11,   6,   0,  32,   0,  16,   3,  11,  38,
    1,   3, 127,  65,   5,  65,   5,  65, 160,   7,  16,  33,
   33,   0,  32,   0,  16,  34,  33,   1,  32,   1,  16,  39,
   33,   2,  65, 192,   7,  32,   2,  16,  40,  16,  43,  16,
   44,  11,   4,   0,  32,   0,  11,   3,   0,   1,  11,   3,
    0,   1,  11,   4,   0,  16,  32,  11,  11, 183,   9,  22,
    0,  65,  12,  11,  48,  44,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   1,   0,   0,   0,  28,   0,   0,
    0,  73,   0, 110,   0, 118,   0,  97,   0, 108,   0, 105,
    0, 100,   0,  32,   0, 108,   0, 101,   0, 110,   0, 103,
    0, 116,   0, 104,   0,   0,  65,  60,  11,  64,  60,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
    0,   0,  38,   0,   0,   0, 126,   0, 108,   0, 105,   0,
   98,   0,  47,   0,  97,   0, 114,   0, 114,   0,  97,   0,
  121,   0,  98,   0, 117,   0, 102,   0, 102,   0, 101,   0,
  114,   0,  46,   0, 116,   0, 115,   0,   0,   0,   0,   0,
    0,   0,   0,  65, 252,   0,  11,  64,  60,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
   40,   0,   0,   0,  65,   0, 108,   0, 108,   0, 111,   0,
   99,   0,  97,   0, 116,   0, 105,   0, 111,   0, 110,   0,
   32,   0, 116,   0, 111,   0, 111,   0,  32,   0, 108,   0,
   97,   0, 114,   0, 103,   0, 101,   0,   0,   0,   0,   0,
    0,  65, 188,   1,  11,  64,  60,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  30,   0,
    0,   0, 126,   0, 108,   0, 105,   0,  98,   0,  47,   0,
  114,   0, 116,   0,  47,   0, 115,   0, 116,   0, 117,   0,
   98,   0,  46,   0, 116,   0, 115,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  65,
  252,   1,  11,  64,  60,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   1,   0,   0,   0,  36,   0,   0,   0,
   73,   0, 110,   0, 100,   0, 101,   0, 120,   0,  32,   0,
  111,   0, 117,   0, 116,   0,  32,   0, 111,   0, 102,   0,
   32,   0, 114,   0,  97,   0, 110,   0, 103,   0, 101,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,  65, 188,   2,
   11,  64,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   1,   0,   0,   0,  38,   0,   0,   0, 126,   0,
  108,   0, 105,   0,  98,   0,  47,   0, 115,   0, 116,   0,
   97,   0, 116,   0, 105,   0,  99,   0,  97,   0, 114,   0,
  114,   0,  97,   0, 121,   0,  46,   0, 116,   0, 115,   0,
    0,   0,   0,   0,   0,   0,   0,  65, 252,   2,  11,  64,
   60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    1,   0,   0,   0,  36,   0,   0,   0, 126,   0, 108,   0,
  105,   0,  98,   0,  47,   0, 116,   0, 121,   0, 112,   0,
  101,   0, 100,   0,  97,   0, 114,   0, 114,   0,  97,   0,
  121,   0,  46,   0, 116,   0, 115,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,  65, 188,   3,  11,  32,  28,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
    0,   0,   4,   0,   0,   0,  58,   0,  58,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,  65, 220,   3,  11,  48,
   44,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    1,   0,   0,   0,  16,   0,   0,   0,  84,   0,  82,   0,
   65,   0,  78,   0,  83,   0,  70,   0,  69,   0,  82,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,  65, 140,   4,  11,  48,  44,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  16,   0,
    0,   0,  65,   0,  80,   0,  80,   0,  82,   0,  79,   0,
   86,   0,  65,   0,  76,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,  65, 188,   4,  11,  48,
   44,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    1,   0,   0,   0,  16,   0,   0,   0, 111,   0, 119,   0,
  110,   0, 101,   0, 114,   0,  79,   0, 102,   0,  95,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,  65, 236,   4,  11,  48,  44,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  14,   0,
    0,   0,  67,   0, 111,   0, 117,   0, 110,   0, 116,   0,
  101,   0, 114,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,  65, 156,   5,  11,  32,
   28,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    1,   0,   0,   0,  10,   0,   0,   0,  79,   0, 119,   0,
  110,   0, 101,   0, 114,   0,   0,   0,   0,  65, 188,   5,
   11,  48,  44,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   1,   0,   0,   0,  14,   0,   0,   0,  98,   0,
   97,   0, 115,   0, 101,   0,  85,   0,  82,   0,  73,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,  65, 236,   5,  11,  48,  44,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
   18,   0,   0,   0,  77,   0,  65,   0,  83,   0,  83,   0,
   65,   0,  95,   0,  78,   0,  70,   0,  84,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,  65, 156,   6,
   11,  32,  28,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   1,   0,   0,   0,   6,   0,   0,   0,  78,   0,
   70,   0,  84,   0,   0,   0,   0,   0,   0,   0,   0,  65,
  188,   6,  11,  32,  28,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   1,   0,   0,   0,  10,   0,   0,   0,
   49,   0,  48,   0,  48,   0,  48,   0,  48,   0,   0,   0,
    0,  65, 220,   6,  11,  48,  44,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  28,   0,
    0,   0, 109,   0,  97,   0, 115,   0, 115,   0,  97,   0,
   46,   0, 110,   0, 101,   0, 116,   0,  47,   0, 110,   0,
  102,   0, 116,   0,  47,   0,   0,  65, 140,   7,  11,  32,
   28,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    5,   0,   0,   0,   5,   0,   0,   0,   0,   1,   2,   3,
    4,   0,   0,   0,   0,   0,   0,   0,   0,  65, 172,   7,
   11,  48,  44,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   1,   0,   0,   0,  28,   0,   0,   0,  83,   0,
   67,   0,  32,   0,  99,   0, 114,   0, 101,   0,  97,   0,
  116,   0, 101,   0, 100,   0,  32,   0,  97,   0, 116,   0,
   58,   0,   0,  65, 220,   7,  11,  32,  28,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,  65, 128,   8,  11,  68,   8,   0,
    0,   0,  32,   0,   0,   0,   0,   0,   0,   0,  32,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  65,   0,
    0,   0,   2,   0,   0,   0, 100,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  32,   0,
    0,   0,   0,   0,   0,   0,   2,   3, 107, 101, 121,   5,
  118,  97, 108, 117, 101,   5,   0,   1,   2,   3,   4,   5,
    0,   1,   2,   3,   4
]
```

After you need to run a `get_operations` on this operation ID. As the operation contains an op datastore it will try to serialize it but I fails because the type of keys in op datastores are Vec<u8>. This error is better handled in `jsonrpsee` and moreover we made a PR to """"fix"""" it with @Eitu33 : https://github.com/massalabs/massa/pull/3255.
This issue is then fixed in TEST.17

**Closed by AurelienFT** 2022-11-28 22:45 UTC

**Comment by damip** [comment] 2022-11-28 23:23
Nice catch @Eitu33 @AurelienFT !
Maybe we should encode the keys as b64 ? or contribute upstream to allow for binary keys ?

**Comment by aoudiamoncef** [comment] 2022-11-29 06:56
Well done mate 👍, this was a tricky one but not a surprise 😅

**Comment by AurelienFT** [comment] 2022-11-29 07:36
> Nice catch @Eitu33 @AurelienFT ! Maybe we should encode the keys as b64 ? or contribute upstream to allow for binary keys ? Or just turn datastores into a vector of key/value structs ?

We could just write a custom deserializer of serde. Just need to make sure we write Json compatible

**Comment by damip** [comment] 2022-11-29 07:42
> > Nice catch @Eitu33 @AurelienFT ! Maybe we should encode the keys as b64 ? or contribute upstream to allow for binary keys ? Or just turn datastores into a vector of key/value structs ?
> 
> We could just write a custom deserializer of serde. Just need to make sure we write Json compatible

Can we open a followup issue on that ?

Does the problem also appear when sending a tx that contains a datastore with binary keys (eg.ExecuteSC) ?

**Comment by AurelienFT** [comment] 2022-11-29 08:00
> Can we open a followup issue on that ?
> 
> Does the problem also appear when sending a tx that contains a datastore with binary keys (eg.ExecuteSC) to the API ?


An issue is already open here : https://github.com/massalabs/massa/issues/3254 .
I don't understand your question. It happens when you try to response with non JSON valid data. Maybe there is other place where it can happen but with `jsonrpsee` they handle it well and answer an error instead of crashing so it's not a that big problem
