### ISSUE TITLE
Crash with Linux binary

### ISSUE THREAD

**Issue by JeromeSi** [massalabs/massa#3641] opened 2023-03-03 18:24 UTC
**Describe the bug**
the massa-node stop with a lot of warning but I don't understand what caused these mistakes

**To Reproduce**
I can't reproduce the problem

**Desktop (please complete the following information):**

- OS: Debian 11.4
- i5-4300M / 16Gb
- Other softwares (chia, nextcloud with 3 users)
- fiber 1Gb/s / 700Mb/s

**Additional context**
I can send all the log but ~142Mb is to o big for github

![graph-enp0s25](https://user-images.githubusercontent.com/13288010/222783718-9a60af57-05bc-4308-bf55-a4de4cf255b5.png)
![graph-memory](https://user-images.githubusercontent.com/13288010/222783734-d8368872-26c2-4fae-9256-a7883590107d.png)
[logs-20.0-node-2023-03-01_17:22:33-WARN_only.log](https://github.com/massalabs/massa/files/10885143/logs-20.0-node-2023-03-01_17.22.33-WARN_only.log)

**Comment by JeromeSi** [comment] 2023-03-03 21:12
I'm searching the number of line with `WARN`
hour 10, lines with WARN : 0
hour 11, lines with WARN : 1
hour 12, lines with WARN : 11
hour 13, lines with WARN : 12
hour 14, lines with WARN : 3
hour 15, lines with WARN : 2469
hour 16, lines with WARN : 26
I'm searching the number of line with `Send network event failed`
hour 10, lines with Send.. : 0
hour 11, lines with Send.. : 0
hour 12, lines with Send.. : 0
hour 13, lines with Send.. : 0
hour 14, lines with Send.. : 0
hour 15, lines with Send.. : 509346
hour 16, lines with Send.. : 30228
hour 17, lines with Send.. : 0

**Comment by AurelienFT** [comment] 2023-03-04 09:33
I seems that you had a internet outage for 3 hours

**Comment by aoudiamoncef** [comment] 2023-03-04 09:43
In addition, there is other software running besides your Massa node, so this could cause some random instability which could make you node fall.

**Comment by JeromeSi** [comment] 2023-03-05 07:55
I don't think it's a problem of internet connection
![image](https://user-images.githubusercontent.com/13288010/222948592-a185d806-1c6f-4569-b26f-eeca763f64db.png)
And there is no excess charge with CPU at this moment
![image](https://user-images.githubusercontent.com/13288010/222948691-ca0f06de-dfb8-4d50-a9a4-bc2ee0fa5b86.png)
![image](https://user-images.githubusercontent.com/13288010/222948696-917fb9d4-a507-445e-a934-7c7bc4d01a31.png)
![image](https://user-images.githubusercontent.com/13288010/222948702-8bf116fb-31f5-4085-bc13-ae36aa23ab81.png)
![image](https://user-images.githubusercontent.com/13288010/222948706-e8482be8-b18c-49e1-9ebc-0df641655de2.png)
But may be it's a random problem
Actually I run the same binary on the same PC with the same wallet and no problem
I think it's a #massamystere

**Comment by AurelienFT** [comment] 2023-05-11 11:15
Without more informations and didn't reproduce since few months it's complicated to diagnose. Closing this. Feel free to re-open if new informations

**Closed by AurelienFT** 2023-05-11 11:15 UTC
