### ISSUE TITLE
Error while bootstrapping: io error: ask consensus state timed out

### ISSUE THREAD

**Issue by Rizen111** [massalabs/massa#2726] opened 2022-06-23 02:33 UTC
why im keep getting this problem

2022-06-23T02:31:54.840430Z  INFO massa_node: Node version : TEST.11.3
2022-06-23T02:31:55.203783Z  INFO massa_bootstrap::client: Start bootstrapping from 198.27.74.5:31245
2022-06-23T02:32:16.821750Z  WARN massa_bootstrap::client: Error while bootstrapping: io error: ask consensus state timed out
2022-06-23T02:32:16.822241Z  INFO massa_bootstrap::client: Bootstrap from server 198.27.74.5:31245 failed. Your node will try to bootstrap from another server in 60s.

**Comment by damip** [comment] 2022-06-23 06:53
Duplicate of https://github.com/massalabs/massa/issues/2723 and https://github.com/massalabs/massa/issues/2722

**Closed** 2022-06-23 06:56 UTC
